### ISSUE TITLE
분봉 조회 기능은 없나요?

### ISSUE THREAD

**Issue by didw** [pjueon/pykis#37]
안녕하세요.
좋은 프로젝트 만들어주셔서 감사합니다.
질문을 어디에 올려야할지 몰라 이슈에 올립니다.

과거 분봉 조회 기능이 있으면 좋을 것 같은데요.
해당 기능이 제공되고 있나요? 아니면 앞으로 제공될 예정인가요?

감사합니다.

**Comment by pjueon** [comment]
안녕하세요 현재 시간/분별 시세 정보 조회 기능은 없습니다. 
가능하다면 추가하고 싶지만 한국투자증권 Open API 개발자 문서를 봤을때 해당 기능을 아직 지원하지 않는 것 같습니다.

일단은 해당 기능 추가에 대해 문의는 작성한 상태입니다. 
해당 기능은 추후 Open API에 해당기능이 추가되어야 구현이 가능할 것 같습니다.

**Comment by pjueon** [comment]
확인 결과 당일 분봉 데이터는 제공되는듯 합니다.
해당 기능은 추후 추가하도록 하겠습니다.

koreainvestment/open-trading-api#11
